# CodeCleaner_Start_5c720369-d888-4ae7-a97d-d3ea0e4f996a
[versions]
agp = "8.1.4"
appcompat = "1.6.1"
coreKtxVersion = "1.12.0"
jsoup = "1.15.4"
jsoupVersion = "1.16.1"
kotlin = "1.8.21"
coreKtx = "1.12.0"
junit = "4.13.2"
junitVersion = "1.1.5"
espressoCore = "3.5.1"
kotlinStdlib = "1.8.21"
kotlinxCoroutinesAndroid = "1.7.3"
kotlinxCoroutinesAndroidVersion = "1.7.1"
kotlinxCoroutinesCore = "1.7.3"
kotlinxCoroutinesCoreVersion = "1.7.1"
lifecycleRuntimeKtx = "2.7.0"
activityCompose = "1.8.2"
composeBom = "2023.10.01"
drawerlayout = "1.2.0"
material = "1.10.0"
roomRuntime = "2.5.2"
room = "2.5.2"

[libraries]
androidx-appcompat = { module = "androidx.appcompat:appcompat", version.ref = "appcompat" }
androidx-core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "coreKtx" }
androidx-core-ktx-v1101 = { module = "androidx.core:core-ktx", version.ref = "coreKtxVersion" }
androidx-room-ktx = { module = "androidx.room:room-ktx", version.ref = "room" }
androidx-room-runtime = { module = "androidx.room:room-runtime", version.ref = "room" }
androidx-room-compiler = { module = "androidx.room:room-compiler", version.ref = "room" }
jsoup = { module = "org.jsoup:jsoup", version.ref = "jsoup" }
jsoup-v1161 = { module = "org.jsoup:jsoup", version.ref = "jsoupVersion" }
junit = { group = "junit", name = "junit", version.ref = "junit" }
androidx-junit = { group = "androidx.test.ext", name = "junit", version.ref = "junitVersion" }
androidx-espresso-core = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "espressoCore" }
androidx-lifecycle-runtime-ktx = { group = "androidx.lifecycle", name = "lifecycle-runtime-ktx", version.ref = "lifecycleRuntimeKtx" }
androidx-activity-compose = { group = "androidx.activity", name = "activity-compose", version.ref = "activityCompose" }
androidx-compose-bom = { group = "androidx.compose", name = "compose-bom", version.ref = "composeBom" }

# Corrected Compose Library Keys - More Descriptive and Follow Convention
androidx-compose-ui = { group = "androidx.compose.ui", name = "ui" } # Correct Key: androidx-compose-ui
androidx-compose-ui-graphics = { group = "androidx.compose.ui", name = "ui-graphics" } # Correct Key: androidx-compose-ui-graphics
androidx-compose-ui-tooling-preview = { group = "androidx.compose.ui", name = "ui-tooling-preview" } # Correct Key: androidx-compose-ui-tooling-preview
androidx-compose-material3-material3 = { group = "androidx.compose.material3", name = "material3" } # Correct Key: androidx-compose-material3-material3
androidx-compose-ui-test-junit4 = { group = "androidx.compose.ui", name = "ui-test-junit4" } # Correct Key: androidx-compose-ui-test-junit4
androidx-compose-ui-tooling = { group = "androidx.compose.ui", name = "ui-tooling" } # Correct Key: androidx-compose-ui-tooling
androidx-compose-ui-test-manifest = { group = "androidx.compose.ui", name = "ui-test-manifest" } # Correct Key: androidx-compose-ui-test-manifest


androidx-drawerlayout-drawerlayout = { group = "androidx.drawerlayout", name = "drawerlayout", version.ref = "drawerlayout" }
kotlin-stdlib = { module = "org.jetbrains.kotlin:kotlin-stdlib", version.ref = "kotlinStdlib" }
kotlinx-coroutines-android = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-android", version.ref = "kotlinxCoroutinesAndroid" }
kotlinx-coroutines-android-v171 = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-android", version.ref = "kotlinxCoroutinesAndroidVersion" }
kotlinx-coroutines-core = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "kotlinxCoroutinesCore" }
kotlinx-coroutines-core-v171 = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "kotlinxCoroutinesCoreVersion" }
material-material = { module = "com.google.android.material:material", version.ref = "material" }
material = { module = "com.google.android.material:material", version.ref = "material" }

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
jetbrains-compose = { id = "org.jetbrains.compose", version = "1.5.11" }
kotlin-kapt = { id = "org.jetbrains.kotlin.kapt", version.ref = "kotlin" }
# CodeCleaner_End_5c720369-d888-4ae7-a97d-d3ea0e4f996a




